```rmarkdown
---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Python Fundamentals

::: {.callout-important title="Attention!!!"}
From now on, all code presented in this book will be in the Python language.
:::

The source for the construction of this material is @mckinney2022.

## Installation

Follow the steps below to install Anaconda and JupyterLab:

1. Download and install Anaconda from the [official website](https://www.anaconda.com/products/distribution). Follow the installation instructions for your specific operating system.

2. After installing Anaconda, open the Anaconda Navigator and create a new virtual environment. Navigate to the "Environments" section and click "Create" to add a new environment. Name the environment and choose the Python version you want to use.

3. After creating the virtual environment, activate it by clicking on the newly created virtual environment in the environment list and selecting "Open Terminal." In the terminal, type the command `conda activate your_environment_name` (replace `your_environment_name` with the name of the environment you created).

4. With the virtual environment activated, install JupyterLab by typing `conda install jupyterlab` in the terminal.

5. After installing JupyterLab, run it by typing `jupyter lab` in the terminal or through the Anaconda interface. This will open JupyterLab in your default browser.

6. In JupyterLab, you can create a new Python notebook by clicking the "+" icon in the left sidebar and selecting "Python 3" under the "Notebook" header.

## Fundamental Data Types

In Python, fundamental data types include `integer`, `float`, `string`, and `boolean`:

- Integers are whole numbers, such as 1, 2, -3, etc.  
- Floats are decimal numbers, such as 3.14, -0.5, etc.  
- Strings are sequences of characters, such as "hello", "world", "python", etc.  
- Booleans are logical values that represent true (`True`) or false (`False`).  

These data types are the basic building blocks for representing different types of information in Python and are widely used in programming to perform operations and data manipulations.

### The Integer Data Type

An `integer` data type in Python represents whole numbers, that is, numbers without decimal places. For example, 5, -10, and 0 are all examples of integers. In Python, integers are represented by the `int` class. Below are examples of basic operations with integers.

```{python}
2 + 2
```

In the first line, we calculate the sum of 2 and 2.

```{python}
amount = 200
print(amount)
type(amount)
```

Above, we assign the value 200 to the variable `amount` and print it using `print(amount)`. Finally, we check the data type of the `amount` variable with `type(amount)`, which returns `<class 'int'>`, indicating that it is an integer.

### The Floating-Point Data Type

A floating-point data type (`float`) in Python represents decimal numbers, that is, numbers that can have a fractional part. For example, 3.14, -0.001, and 2.71828 are all floats. In Python, floats are represented by the `float` class.

```{python}
1.75 + 2**3 
interest_rate = 1.25

print(interest_rate)
type(interest_rate)
```

In the first line of the example above, we calculate the sum of 1.75 and 2 raised to the third power. Then, we assign the value 1.25 to the variable `interest_rate` and print it using `print(interest_rate)`. Finally, we check the data type of the `interest_rate` variable with `type(interest_rate)`, which returns `<class 'float'>`, indicating that it is a floating-point number.

### The String Data Type

```{python}
country = "Brazil" 

print(country)
type(country)
```

In the code above, we create a variable called `country` and assign it the value "Brazil," which is a string. Then, we print the value of the `country` variable using `print(country)`, which displays "Brazil" on the screen. Finally, we check the data type of the `country` variable with `type(country)`, which returns `<class 'str'>`, indicating that it is a string.

### The Boolean Data Type

The boolean data type, also known as `bool`, is used to represent true or false values. In Python, boolean values are `True` and `False`, representing true and false, respectively.

```{python}
1 == 2
```

```{python}
5 % 2 == 0
```

```{python}
interest_rate_increasing = True
print(interest_rate_increasing)
type(interest_rate_increasing)
```

In the first line of the example above, there is an equality check between 1 and 2, which returns `False` because 1 is not equal to 2. Then we have `5 % 2 == 0`, which also returns `False` because the remainder of the division of 5 by 2 is not zero. Finally, we have the variable `interest_rate_increasing` assigned to `True`, indicating that the interest rate is increasing. When printing and checking the type of this variable, we get `True` as the result and the type `bool`, indicating that it is a boolean value.
```
### Type Coercion

Data coercion in Python refers to the forced conversion of one data type to another.

```{python}
str_num = "1.41"
type(str_num)
```

```{python}
float(str_num)
```

Notice that the variable `str_num` is a string representing the number 1.41. Initially, its type is checked using the `type` function, which returns `<class 'str'>`, indicating it is a `string`. Then, we use the `float()` function to explicitly convert `str_num` into a float. After the conversion, the value of `str_num` is `"1.41"` and its type changes to `<class 'float'>`.

Below are other examples of coercion.

Coercion to an integer:

```{python}
float_num = 3.14
int_num = int(float_num)
print(int_num)
```

Coercion to a boolean:

```{python}
integer_value = 0
boolean_value = bool(integer_value)
print(boolean_value)
```

Coercion to a string (`str`):

```{python}
float_num = 3.14
str_num = str(float_num)
print(str_num) 
```

In the code above, we are converting a float value to a string.

## Basic Objects

In Python, there are three basic data structures: lists, tuples, and dictionaries: 
- Lists are ordered and mutable collections of elements, allowing for the inclusion of items of different types and modification of their values.
- Tuples are similar to lists but are immutable, meaning they cannot be altered after creation.
- Dictionaries are unordered collections of key-value pairs, where each value is associated with a unique key, providing efficient data access through the keys.

### Lists

In Python, a list is a data structure that allows storing an ordered collection of elements. To create a list, we use square brackets `[]`, and the elements are separated by commas. We can instantiate an empty list using `[]` or the `list()` function. For example:

```{python}
empty_list = [] # Empty list
empty_list = list() # alternative

# list with GDP of countries
gdp_countries = [1800, 2500, 3200, 5600, 6700]
```

In the example above, we also have the list `gdp_countries` that stores the Gross Domestic Product (GDP) of different countries. To access elements of a list in Python, we can use the index of the desired element inside square brackets `[]`. The index starts from zero for the first element, one for the second, and so on. For example:

```{python}
print(gdp_countries[1])
```

We can also access elements from the end of the list using negative indices, where -1 represents the last element, -2 the second last, and so on:

```{python}
# Accessing the last element
last_element = gdp_countries[-1]
print(last_element)

# Accessing the second last element
second_to_last_element = gdp_countries[-2]
print(second_to_last_element)
```

We can use the `append()` method if we want to add an element to the end of the list, or the `insert()` method if we want to add an element at a specific position. Here are examples of how to use both methods:

```{python}
# Adding elements to the end of the list using append()
gdp_countries.append(2000)  # Adds the value 2000 to the end of the list

# Adding an element at a specific position using insert()
gdp_countries.insert(1, 1500)  # Adds the value 1500 at position 1 of the list
```

To check the size of a list in Python, we can use the `len()` function.

```{python}
list_size = len(gdp_countries)
print("List size:", list_size) 
```

To sort a list, we can use the `sort()` method for in-place sorting (which modifies the list) or the `sorted()` function to return a new sorted list without modifying the original:

```{python}
# Using the sorted() function to return a new sorted list
sorted_list = sorted(gdp_countries)
print("New sorted list:", sorted_list)

# Sorting the list using the sort() method
gdp_countries.sort()
print("Sorted list:", gdp_countries)
```

The `.pop()` method is used to remove and return the last element of a list. We can also specify an index to remove and return an element at a specific position in the list. Here's how to use the `.pop()` method:

```{python}
# Removing and returning the last GDP in the list
last_gdp = gdp_countries.pop()
print("Last removed GDP:", last_gdp) 
print("Updated list:", gdp_countries)

# Removing and returning the GDP of a specific country from the list
removed_gdp = gdp_countries.pop(1) 
print("Removed GDP:", removed_gdp) 
print("Updated list:", gdp_countries)
```

### Tuples

Tuples are data structures similar to lists but with a fundamental difference: they are immutable, meaning they cannot be modified once created. They are represented by parentheses `()` instead of square brackets `[]`.

```{python}
x = (1, 2, 3) # tuple (immutable list)
print(x)

# x[0] = 5 # raises an error!
```

We can use tuples to represent information that should not be altered, such as currency exchange rates. See:

```{python}
taxas_cambio = (("USD", "EUR", 0.82), ("USD", "JPY", 105.42), ("EUR", "JPY", 128.64))
```

In this example, we have a tuple of tuples representing exchange rates between the dollar (USD), euro (EUR), and Japanese yen (JPY) for a fictitious fixed date. Each inner tuple contains three elements: the source currency, the destination currency, and the exchange rate. Since this information should not be altered, a tuple is an appropriate choice.

::: callout-tip
To access the elements of a tuple, you can use the same syntax as for accessing elements of a list, that is, by using square brackets `[]` and the desired element's index. Remember that indices in Python start at 0!
:::

### Dictionaries

Dictionaries in Python are data structures that allow storing key-value pairs. Each value is associated with a specific key, allowing for quick access to data through the keys instead of numeric indices, as in lists and tuples. This structure is useful when you need to associate information in a way similar to a database, where you can retrieve information based on a specific key.

In the example below, we have stock quotes for some Brazilian companies listed on the stock exchange.

```{python}
brazilian_stock_prices = {
    "PETR4": 36.75,
    "VALE3": 62.40,
    "ITUB4": 34.15,
    "BBDC4": 13.82
}
```

Each key is the stock trading code on the exchange, and the associated value is the stock price on a fixed date. For example, `brazilian_stock_prices["PETR4"]` would return the stock price for Petrobras.

Alternatively, you can create a dictionary using the `dict` function:

```{python}
brazilian_stock_prices = dict(PETR4=36.12, VALE3=62.40, ITUB4=34.15, BBDC4=13.82)
```

You can add new key-value pairs to a dictionary or update existing values. For example:

```{python}
brazilian_stock_prices["ABEV3"] = 12.80
brazilian_stock_prices["PETR4"] = 36.75
```

You can remove key-value pairs from a dictionary using the `pop()` method. For example:

```{python}
removed_value = brazilian_stock_prices.pop("BBDC4")
```

Other useful methods for working with dictionaries are `keys()`, `values()`, and `items()` which return lists of the dictionary's keys, values, and items, respectively.

```{python}
brazilian_stock_prices.keys() # returns a list containing all keys
```

```{python}
brazilian_stock_prices.values() # returns a list containing all values
```

```{python}
brazilian_stock_prices.items() # returns a list of tuples
```

## Functions

Functions are reusable code blocks that perform a specific task.\
They accept inputs, called arguments, and can return results.

In Python, the basic syntax of a function is as follows:

```{python}
#| eval: false

def function_name(argument1, argument2, ...):
    # Function body
    # Do something with the arguments
    result = argument1 + argument2
    return result
```

For example, let's create a Python function called `calculate_interest` that calculates the final amount of an investment based on the initial amount, interest rate, and number of years:

```{python}
def calculate_interest(initial_amount, interest_rate, years):
    final_amount = initial_amount * (1 + interest_rate) ** years
    return final_amount
```

Now, let's set values and call the function:

```{python}
initial_investment = 1000  # Initial investment amount
annual_interest_rate = 0.05  # Annual interest rate (5%)
years = 5  # Number of years
result = calculate_interest(initial_investment, annual_interest_rate, years)
print("The final amount after", years, "years will be: $", round(result, 2))
```

### `lambda` Function

A lambda function in Python is an anonymous function, meaning it is a function without a name. It is defined using the `lambda` keyword and can have any number of arguments but only one expression. The basic syntax is as follows:

```{python}
#| eval: false
lambda argument1, argument2, ...: expression
```

Here’s an example of a lambda function that calculates the square of a number:

```{python}
square = lambda x: x ** 2
```

In this example, `lambda x: x ** 2` creates a function that accepts an argument `x` and returns `x` squared. You can use this function just like any other function. For example:

```{python}
result = square(5)
print(result)
```

Lambda functions are often used in situations where you need a temporary and simple function, such as in data mapping, filtering, and sorting operations.

## Classes and Objects

A class is a structure that defines the behavior and properties of a type of object. We can think of a class as a representation of an abstract concept, such as a financial transaction or a specific type of investment.

For example, we can create a class called `Transaction` to represent a financial transaction, with properties such as the transaction amount, date, and type.

An object, on the other hand, is a specific instance of a class. It represents a concrete entity with its own characteristics and behaviors. Continuing with the `Transaction` class example, we can create individual objects to represent specific transactions, such as purchasing company stocks on a specific date.

```{python}
class Transaction:
    def __init__(self, amount, date, type):
        self.amount = amount
        self.date = date
        self.type = type
    
    def print_info(self):
      print(f"Transaction type: {self.type}, Amount: ${self.amount}, Date: {self.date}")
```

In this example, the `Transaction` class has a special method `__init__` that is called when a new object is created. This method initializes the object's properties with the values provided as arguments. Additionally, the class has a method called `print_info`, which prints the transaction information, including the type, amount, and date. This method also receives `self` as a parameter to access the attributes of the current class instance. When calling `print_info()` on a `Transaction` object, it will display the formatted transaction information.

Next, we create two objects of the `Transaction` class, `transaction1` and `transaction2`, and access their properties to obtain information about the transactions.

```{python}
# Creating objects of the Transaction class
transaction1 = Transaction(amount=1000, date="2024-03-11", type="Stock Purchase")
transaction2 = Transaction(amount=500, date="2024-03-12", type="Stock Sale")

# Accessing object properties
print("Transaction 1 Amount:", transaction1.amount)
print("Transaction 2 Date:", transaction2.date)

# Accessing object methods
transaction1.print_info()
transaction2.print_info()
```

## Exercises

**1.** Working with basic data types

**a)** Create variables to represent economic data, such as GDP for at least three countries, inflation rates, or unemployment rates. Use recent and historical values to create a diverse set of economic data representing different economic contexts worldwide.

**b)** Perform basic mathematical operations with this data, such as calculating averages, growth rates, or proportions. For example, you can calculate GDP value averages, GDP growth rates over time, or proportions between different economic indicators (such as per capita GDP relative to total GDP), among other operations.

**2.** During data analysis, it may be necessary to convert between different data types. Use fundamental data types (integers, floats, strings) and apply type coercion as necessary. Consider, for example, that the variables representing GDP were given in `string` format. Convert to a `float` type to compute the average GDPs considered. After that, convert the GDP values back to a `string` to format the output in the following format `1,111%`.

**3.** Use the code below to generate a pandas dataframe representing the closing price of a stock.

```{python}
import pandas as pd

# Creating a list of dates
dates = pd.date_range(start='2023-01-01', end='2023-12-31', freq='B')  # Frequency 'B' to consider only business days

# Creating a series of simulated closing prices
import numpy as np
np.random.seed(0)  # Set random seed for reproducibility
closing_prices = np.random.normal(loc=50, scale=5, size=len(dates))  # Simulate prices with normal distribution

# Creating the DataFrame
df_stock_prices = pd.DataFrame({'Date': dates, 'Closing Price': closing_prices})

# Displaying the first rows of the DataFrame
print(df_stock_prices.head())
```

**a)** Obtain the closing prices of the stock during the specified January month.

**b)** Obtain the closing prices of the stock between 2023-06-01 and 2023-12-31.

**c)** Obtain the closing prices of the stock on Fridays throughout the period. Calculate the average closing price on Mondays and compare it to that on Fridays. Which one shows a higher standard deviation?

```{python}
# Creating a column to store the day of the week
df_stock_prices['Day of the Week'] = df_stock_prices['Date'].dt.weekday

# Displaying the first rows of the DataFrame with the new column
print(df_stock_prices.head())
```

...
